### ISSUE TITLE
还没有噪音

### ISSUE THREAD

**Issue by dimative** [nondanee/vsc-netease-music#64]
Hello. 
Today i am installed your extension. Your extension looks nice, works fine. but does not have any noise. I'm using Deepins OS 15.11 and VS Code latest version. I want to use your extension. Please help me. 

Thanks.

**Comment by nondanee** [comment]
I'm so sorry there is no english README because this extension mainly aims to Chinese users for our local music streaming service (NeteaseMusic) in China mainland.

Because VS Code uses a version of electron that does not include ffmpeg. You need to replace the built-in ffmpeg dynamic link library with the dll in the official release version of electron, then it can play sound properly.

Running the following script can automatically replace the dll for you. (need `su` permisson)
```sh
curl https://gist.githubusercontent.com/nondanee/f157bbbccecfe29e48d87273cd02e213/raw | python
```
